n = input('Digite o que desejar: ')
print('É alfanumérico?')
print(n.isalnum())
print ('É alfabetico?')
print(n.isalpha())
print ('É ascii?')
print(n.isascii())
print ('É decimal?')
print(n.isdecimal())
print ('É um dígito?')
print(n.isdigit())
print ('É um identificador?')
print(n.isidentifier())
print ('É minúsculo?')
print(n.islower())
print ('É numérico?')
print(n.isnumeric())
print ('É imprimível?')
print(n.isprintable())
print ('É um espaço?')
print(n.isspace())
print ('Está capitalizada?')
print(n.istitle())
print ('É maiúsculo?')
print(n.isupper())